[TB] Add reviews here
hassanobeid1994/tr_b_causal_2020 pull request #152
Opened 2020-11-22 23:25 UTC by timothyb0912

2020-11-25 03:13 UTC, bouzaghrane requested changes
Comments for section 6 @timothyb0912

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +Our unstated presumption is that we will test our working causal graph.
Changed from working to proposed just in case some people understood working to be "valid" or correct, which could lead them to more confusion since you're talking about failing tests in the following sentence.
```suggestion
Our unstated presumption is that we will test our proposed causal graph.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +If any of our tests fail, we will then revise the graph until its assumptions appear plausible.
Changed to defensible because really anything could be plausible. I understand where you're coming from, meaning that given our data, our assumptions are plausible. I think defensible gives ownership of the assumptions to the researcher.
```suggestion
If any of our tests fail, we will then revise the graph until its assumptions appear defensible.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +In this section, we will discuss how we can avoid such repetitive, manual graph editing.
In my mind these two things are distinct yet complimentary tasks. You can't edit without testing. You mentioned it earlier, so this might be an overkill.

```suggestion
In this section, we will discuss how we can avoid such repetitive, manual graph editing and testing.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +Instead, we use our computers algorithmic capabilities.
I think this sentence should be removed. The following sentence is duplicate to me. Unless you think there are some other algorithmic capabilities that do this work.
```suggestion
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +Indeed, it's typically easier to edit than to create from scratch.
```suggestion
Indeed, it is typically easier to edit than to create from scratch.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +Graphs found via causal discovery can spark ideas for one's own graph if they feature different causal relations than are present in one's own graph, and they provide a starting point for graph revis
What I understand from this paragraph is that causal discovery helps in both the creation of initial graphs. But this sentence refers back to some initial causal graph that was created by the researcher. Was the intent to refer to both things?

I don't know why I am struggling to separate editing a causal graph from checking the robustness of results.

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +\end{itemize}
Should we reorder these to be in the same order as we present them above?

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +The following subsection presents a non-exhaustive overview of causal discovery algorithms.
```suggestion
This subsection presents a non-exhaustive overview of causal discovery algorithms.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +% DESCRIBE SCORE BASED DISCOVERY ALGORITHMS
What are these scores? Are there example we can give of the scores? Just names of score metrics, or what the scores quantify?

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +And of course, extensions of these techniques exist for inference in the presence of unobserved confounding \citep[Sec. 6]{goudet_2018_learning} and for learning an entire causal graph as opposed to
No comments here, but sheesh...people do work!

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +For practitioners who may reasonably start with the simplest method they can find and increase methodological complexity as needed, this should be an illuminating starting point.
This sentence sounds funky to me so edited it to the following
```suggestion
For practitioners who may reasonably start with the simplest method available and increase methodological complexity as needed, this should be an illuminating starting point.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +Accordingly, using the PC algorithm on our example allows us to observe how the algorithm behaves under violation of its assumptions.
```suggestion
As noted in Section \ref{sec:testing-demonstration}, we suspect that our causal graph for the drive alone utility of our dataset contains unobserved confounding.
Given the PC algorithm assumes that one has no unobserved confounders, using it on our example allows us to observe how the algorithm behaves under violation of its assumptions.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +In the final case, we recover an undirected causal graph.
```suggestion
In the worst case, we recover an undirected causal graph.
```

2020-11-25 03:13 UTC, bouzaghrane commented on article/sections/_6_graph_discovery.tex
> +In the final case, we recover an undirected causal graph.
hmmm thinking about how a reader could interpret worst here and second doubting my suggestion. Is it really bad that we recover an undirected causal graph? I mean sure it's bad for us because it means more work, but is it objectively or scientifically bad?

2020-11-26 06:51 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +In this section, we will discuss how we can avoid such repetitive, manual graph editing.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:51 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +Our unstated presumption is that we will test our working causal graph.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:51 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +If any of our tests fail, we will then revise the graph until its assumptions appear plausible.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:52 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +Instead, we use our computers algorithmic capabilities.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:52 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +Indeed, it's typically easier to edit than to create from scratch.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:53 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +% DESCRIBE SCORE BASED DISCOVERY ALGORITHMS
Usually just BIC. See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:53 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +% DESCRIBE SCORE BASED DISCOVERY ALGORITHMS
And I added the specification of scores in the paper, not just on github comments lol.

2020-11-26 06:54 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +And of course, extensions of these techniques exist for inference in the presence of unobserved confounding \citep[Sec. 6]{goudet_2018_learning} and for learning an entire causal graph as opposed to
Right? The amount of work done that we've never even scratched the surface in terms of using/investigating is massive!

2020-11-26 06:54 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +For practitioners who may reasonably start with the simplest method they can find and increase methodological complexity as needed, this should be an illuminating starting point.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:55 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +Accordingly, using the PC algorithm on our example allows us to observe how the algorithm behaves under violation of its assumptions.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:55 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +The following subsection presents a non-exhaustive overview of causal discovery algorithms.
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:55 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +\end{itemize}
Done! See PR [here](https://github.com/hassan-obeid/tr_b_causal_2020/pull/155) as it'll be easier for me to merge.

2020-11-26 06:56 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +Graphs found via causal discovery can spark ideas for one's own graph if they feature different causal relations than are present in one's own graph, and they provide a starting point for graph revis
Let's talk more about this on Sunday.

2020-11-26 06:57 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +In the final case, we recover an undirected causal graph.
I don't think it's necessarily scientifically bad. It means one has to use other techniques to calculate causal effects. I think I'll stick with final to avoid any incorrect connotations.

2020-11-28 04:33 UTC, timothyb0912 commented on article/sections/_6_graph_discovery.tex
> +Graphs found via causal discovery can spark ideas for one's own graph if they feature different causal relations than are present in one's own graph, and they provide a starting point for graph revis
Actually, does the current edit work for you? I changed to:

```suggestion
If we have not already created our own causal graphs, then we will find that it's typically easier to edit discovered graphs than to create from scratch.
Alternatively, graphs found via causal discovery can spark revisions if we have already created our own graphs.
This is especially likely when the discovered graphs feature different causal relations than are present in our own graph.
```

The diff is messed up (missing original line 36 in red) but hopefully you get the point.

2020-11-29 23:05 UTC, closed without merging